#!/bin/sh
exec docker run -itd --rm \
  --name moonlight \
  --ipc host \
  --hostname $(hostname) \
  --env DISPLAY \
  --env XAUTHORITY=/tmp/xauth \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  --volume $XAUTHORITY:/tmp/xauth:ro \
  --volume ~/.config/moonlight:"/root/.config/Moonlight Game Streaming Project" \
  --device /dev/dri \
  docker.raraph.fr/moonlight
