#!/bin/sh
exec docker run -itd --rm \
  --name parsec \
  --user 0:0 \
  --hostname $(hostname) \
  --env DISPLAY \
  --env XAUTHORITY=/tmp/xauth \
  --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
  --volume $XAUTHORITY:/tmp/xauth:ro \
  --volume ~/.config/parsec:/root/.parsec \
  ghcr.io/jaredallard/docker-parsec:main app_daemon=1
